@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('Build')
        {
            steps
            {
                script
                {
                    cicd.buildArtifact()
                }
            }
        
        }
	stage('Deployment')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("DPwithSharedLibraries","172.31.15.135","testapp")
                }
            }
        }
    }
}
